### ISSUE TITLE
Formatting of JSON data

### ISSUE THREAD

**Issue by ShashinGounden** [ShashinGounden/miniproject-2023#10]
Please add how the JSON data will be formatted and used between the front-end and back-end to the Wiki on the GitHub page. This is according to how it has been discussed with @Bandisa and  @ArmandKrynauw.

**Comment by JsteReubsSoftware** [comment]
I added a list of requirements for how the JSON data needs to be formatted for when a user wants to view another user's page.
Check the updated version of the Wiki.

**Comment by ShashinGounden** [comment]
Looks great, thanks for gettting it up quickly!
