### ISSUE TITLE
Gather data from front end for endpoints

### ISSUE THREAD

**Issue by ShashinGounden** [ShashinGounden/miniproject-2023#8]
Please gather the data from @08Arno30 and @JsteReubsSoftware about the front end. Find out what data they need for every page and feature so that the API engineers know what endpoints to implement.

After gathering the info, send it to the back end team, @ArmandKrynauw  and @LucaLoubser to build the endpoints for the data.

**Comment by Bandisa** [comment]
I had a meeting with  @08Arno30, @JsteReubsSoftware &  @ArmandKrynauw.

Currently the front-end team cannot fully specify what Data they will need. They will only be certain or get an idea when they add mock data.

Thus we agreed that they will keep a mock-down file, that they will populate with the expected response/request from the api, which will then be shared accordingly, either direct or by git.
