### ISSUE TITLE
Front-end page development

### ISSUE THREAD

**Issue by ShashinGounden** [ShashinGounden/miniproject-2023#9]
Please finish the _**design of the following front front-end pages**_ as we discussed in the meetings this week:

-Profile View
-Login 
-Both user views

**Comment by 08Arno30** [comment]
These pages' designs are complete. Only need to add functionality to the "Revive Memory" action. But for that we'll need JSON data to get the user's active memories.

**Comment by JsteReubsSoftware** [comment]
Completed the following pages:
-Login
-Register
-Welcome
      -Terms of Service
      -Privacy Policy
-Forgot Password
-User view (also added functionality for friending a.k.a. following another user)

And then the Search page is about 90% complete.

**Comment by ShashinGounden** [comment]
Great work, we’ll all take a look during todays meeting on discord.
